# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

rn_path = '../node_modules/react-native'

target 'RNCamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!

  # React Native
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', podspec: "#{rn_path}/third-party-podspecs/Folly.podspec"

#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      if target.name == "React"
#        target.remove_from_project
#      end
#    end
#  end

  # Pods for RNCamera
  pod 'OpenCV'

end
