require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNCamera' do
    config = use_native_modules!
    use_react_native!(:path => config["reactNativePath"])

#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      if target.name == "React"
#        target.remove_from_project
#      end
#    end
#  end

  # Pods for RNCamera
  pod 'OpenCV'

end
